IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('CLIENTES') AND NAME = 'CPF')
BEGIN
    ALTER TABLE CLIENTES ADD CPF VARCHAR(11) NOT NULL CONSTRAINT DF_CLIENTES_CPF DEFAULT ('');
    PRINT('Coluna CPF foi adicionada à tabela CLIENTES')
END
ELSE
    PRINT('Coluna CPF já existe na tabela CLIENTES')
GO